/**
 * Created by Cedric Zhang on 2016/8/24.
 */
var code={
    SUCCESS : 100,


    CONNE_TO_DB_ERR:-10,
    CREATE_QUESTION_ERR:-20,
    QUERY_QUESTION_AMOUNT_ERR:-30,
    QUERY_UNCHEKED_QUESTION_ERR:-40,
    QUERY_QUESTION_BY_ID_ERR:-50,
    UPDATE_QUESTION_ERR:-60,
    SELECT_10_QUESTIONS_ERR:-70,
    UPDATE_RAISED_TIMES_ERR:-80,

    WRONG_PSWD:-200,
    BAD_REQUEST:-210

};

exports.code = code;